name: clickable_list_wheel_view
description: Simple wrapper for ListWheelScrollView that allows children to respond on gesture (onTap) events.
version: 0.2.0
homepage: https://github.com/Cilestal/clickable_list_wheel_view

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: